services:
  sd-search-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Backend container runs in another network, so use the docker internal hostname to reach it from the frontend container.
      BACKEND_URL: ${BACKEND_URL:-http://host.docker.internal:8000}
    restart: unless-stopped